export enum EventType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  LOGOUT = 'LOGOUT',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  UPLOAD = 'UPLOAD',
  EXTRACTION_SUCCESS = 'EXTRACTION_SUCCESS',
  EXTRACTION_FAILURE = 'EXTRACTION_FAILURE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}